title: Project

files:
  sortable: true
  fields:
    caption:
      label: Caption
      type: textarea
    link:
      label: Link
      type: text
    maxwidth:
      label: Make this image 66% wide?
      type: checkbox
      text: yes please
    embed:
      label: Embedded content
      type: text

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  text:
    label: Credits
    type:  textarea
